// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel main

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture3D<float4> ColorData;
RWTexture3D<float4> SurfaceData;

float3 baseOffset;
float4 color0;
float4 color1;
float4 sliders;

int texWidth;

float4x4 start;
float4x4 end;

[numthreads(4, 4, 4)]
void main(uint3 id : SV_DispatchThreadID)
{

	ColorData[id] = color0;
	SurfaceData[id] = color1;

}
